---

- name: Install RHCL operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'kuadrant_operator_application.yaml.j2') | from_yaml }}"

- name: Install RHCL
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'kuadrant_application.yaml.j2') | from_yaml }}"
